### ISSUE TITLE
Try-outs are unorderd

### ISSUE THREAD

**Issue by Larsv94** [VisserSanne/WebDev-Bootcamp#1]
I feel like the folder structure for your Try-outs is rather unorganized which makes it confusing to see what's happening

**Comment by VisserSanne** [comment]
I agree! Now i've organized it so you have all the html together and the css together (and within the css folder you have the html and css separate as well). Do you think it looks better like this?

**Comment by Larsv94** [comment]
I don't think you have pushed your changes! I would advice you to group each CSS with it's accompanying HTML per tryout
so something like:

-tryout1
---index.html
---tryout1.css
-tryout2
---index.html
---tryout.css

**Comment by VisserSanne** [comment]
Oh indeed! Haven't pushed my changes!
But you suggest that i should put ever html file in a folder? (And that the css that has been written for a html file will be put in a folder together?

**Comment by Larsv94** [comment]
Exactly! That way you have it grouped per project/try-out instead of per file type

**Comment by VisserSanne** [comment]
Do you think it looks better like this?

**Comment by Larsv94** [comment]
Yeah perfect
